// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cn.edu.cqupt.cblog.domain;

import cn.edu.cqupt.cblog.domain.HonorWall;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect HonorWall_Roo_Configurable {
    
    declare @type: HonorWall: @Configurable;
    
}
