// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cn.edu.cqupt.cblog.domain;

import cn.edu.cqupt.cblog.domain.HonorWall;

privileged aspect HonorWall_Roo_JavaBean {
    
    public String HonorWall.getImage() {
        return this.image;
    }
    
    public void HonorWall.setImage(String image) {
        this.image = image;
    }
    
}
